set_property SRC_FILE_INFO {cfile:{C:/Users/xchen/Documents/EE460M HDL Digital Sys/EE460M-Labs/Lab 3/Basys3_Master.xdc} rfile:../../../../Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {start}]
